First commit after refactoring to JDK only buildpack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -7,35 +7,25 @@ set -eu
 BP_DIR="$(cd "$(dirname "$0")" && pwd)"
 BUILD_DIR=$1
 CACHE_DIR=$2
-OPT_DIR=$BP_DIR/../opt/
 
-fetch_nginx_tarball() {
-    local version="1.9.7"
-    local tarball_file="nginx-$version.tgz"
-    local stack="cedar-14"
-    local nginx_tarball_url="https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/nginx/$stack/nginx-$version-ngx_mruby.tgz"
-    local dest_path="$CACHE_DIR/$stack/$tarball_file"
+# Set up environment variables from Heroku config variables
+$BUILDPACK_STDLIB_URL="https://lang-common.s3.amazonaws.com/buildpack-stdlib/v7/stdlib.sh"
+source <(curl -s --retry 3 -L $BUILDPACK_STDLIB_URL)
+export_env $ENV_DIR
 
-    if [ -f "$dest_path" ]; then
-        echo -n "cat $dest_path"
-    else
-        echo -n "curl -L $nginx_tarball_url"
-    fi
-}
+AWS_CMD=$BUILD_DIR/vendor/awscli/bin/aws
 
-heroku_bin_dir=$BUILD_DIR/.heroku/bin
-mkdir -p $heroku_bin_dir
+# Validate environment variables
+[ -z "$AWS_ACCESS_KEY_ID" ] && echo " ! ERROR: missing AWS_ACCESS_KEY_ID config var" && exit 1
+[ -z "$AWS_SECRET_ACCESS_KEY" ] && echo " ! ERROR: missing AWS_SECRET_ACCESS_KEY config var" && exit 1
+[ -z "$AWS_S3_BUCKET_NAME" ] && echo " ! ERROR: missing AWS_S3_BUCKET_NAME config var" && exit 1
+[ ! -f $AWS_CMD ] && echo "ERROR: aws-cli is not installed" && exit 1
 
-nginx_dir=$BUILD_DIR/.nginx
-nginx_bin_dir=$nginx_dir/bin
-mkdir -p $nginx_bin_dir
+cd $BUILD_DIR
 
-$(fetch_nginx_tarball) | tar xzC $nginx_bin_dir
-cp $OPT_DIR/web $nginx_dir/bin/nginx-start
-chmod +x $nginx_dir/bin/nginx-start
-echo "-----> Installed nginx"
-
-cp $OPT_DIR/recompose $heroku_bin_dir/recompose
-chmod +x ${heroku_bin_dir}/recompose
-
-cp $OPT_DIR/nginx.conf.erb $nginx_dir/
+############ Downloading jdk1.8.0_131_x64s
+SFDC_JDK_KEY=${SFDC_JDK_KEY:-"d5eab6c07320844df2961afd84f95df8"}
+echo "**** Downloading jdk1.8.0_131_x64 from s3Key:${SFDC_JDK_KEY}"
+${AWS_CMD:?} s3 cp s3://${AWS_S3_BUCKET_NAME:?}/${SFDC_JDK_KEY} - | tar xzm --strip-components=1 -C . 2>&1
+echo "Completed downloading jdk1.8.0_131_x64 from s3Key:${SFDC_JDK_KEY}"
+############
